#!/bin/sh
#
# Configure.sh
#
# Configure sscep
#

solaris () {
  ln -fs Solaris/Makefile Makefile
  echo "Done."
  echo "Run 'make' to build sscep."
  echo "Run 'make package' to build sscep and create a Solaris installation package."
}

aix () {
  ln -fs AIX/Makefile Makefile
}

linux () {
  ln -fs Linux/Makefile Makefile
}

macosx () {
  ln -fs MacOSX/Makefile Makefile
  echo "NOTE: You have to define the openssl directory like below before you "
  echo "      launch make."
  echo "          OPENSSL=/usr/local/Cellar/openssl/1.0.2h_1 make"
  echo "      Otherwise it supposes the directory is /usr/local/openssl"
}

##### MAIN #####

OS=`uname -s`

if [ x"$OS" = "xSunOS" ]
then
  echo "Configuring for $OS..."
  solaris
elif [ x"$OS" = "xLinux" ]
then
  echo "Configuring for $OS..."
  linux
elif [ x"$OS" = "xAIX" ]
then
  echo "Configuring for $OS..."
  aix
elif [ x"$OS" = "xDarwin" ]
then
  echo "Configuring for MacOSX..."
  macosx
else
  echo "OS $OS not supported, aborting..." 1&>2
  exit 1
fi

